baseURL = "https://joshuaadams.github.io/"
languageCode = "en-us"
title = "Joshua Adams"
# theme = "wowchemy"
paginate = 10

enableRobotsTXT = true
canonifyURLs = true

[module]
  [[module.imports]]
    path = "github.com/HugoBlox/hugo-blox-builder/modules/blox-bootstrap/v5"

[params]
  # Basic profile
  description = "Academic research, publications, teaching, and CV"
  email = "contact@joshuaadams.dev"

  # Appearance
  [params.appearance]
    theme = "indigo"
    font = "minimal"
    font_size = "L"
    mode = "light"

  # Social & scholarly IDs
  orcid = "https://orcid.org/0000-0002-7185-9125"
  google_scholar = "" # add your profile URL
  linkedin = "https://www.linkedin.com/in/adamdsit/"

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  term = ["HTML", "RSS"]

[menu]
  [[menu.main]]
    name = "About"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "People"
    url = "/people/"
    weight = 2
  [[menu.main]]
    name = "Publications"
    url = "/publication/"
    weight = 3
  [[menu.main]]
    name = "Teaching"
    url = "/teaching/"
    weight = 4
  [[menu.main]]
    name = "Contact"
    url = "/#get-in-touch"
    weight = 5

[languages]
  [languages.en]
    languageName = "English"
    weight = 1
  [languages.ja]
    languageName = "日本語"
    weight = 2

[markup]
  [markup.goldmark.renderer]
    unsafe = true

[security]
  [security.funcs]
    getenv = ['^HUGO_', '^CI$', '^WC_']
